### ISSUE TITLE
Issue with LlamaParse ...The API is suddently extremely slow in terms of responding to documents. Initially, my website used to get a response in seconds. Anyone felt the same? Thanks

### ISSUE THREAD

**Issue by jayantsharma279** [run-llama/llama_parse#588]
**Describe the bug**
Write a concise description of what the bug is.

**Files**
If possible, please provide the PDF file causing the issue.

**Job ID**
If you have it, please provide the ID of the job you ran.
You can find it here: https://cloud.llamaindex.ai/parse in the "History" tab.

**Client:**
Please remove untested options:
 - Python Library
 - API
 - Frontend (cloud.llamaindex.ai)
 - Typescript Library
 - Notebook

**Additional context**
Add any additional context about the problem here.
What options did you use? Premium mode, multimodal, fast mode, parsing instructions, etc.
Screenshots, code snippets, etc.

**Comment by toludev3** [comment]
were you able to solve this, also just started experincing this yesterday

**Comment by jayantsharma279** [comment]
A tad bit of improvement, not the usual speed like it was a few days back.

**Comment by hamzanouali42** [comment]
I confirm that the issue is still there, not fixed yet. One of our 10MB documents took hours to finish.

**Comment by jasontjahjono** [comment]
is there any updates to this?

**Comment by sandroxavierdeveloper** [comment]
I am writing to report a significant decrease in performance with the LlamaParse API. Until this morning, the API consistently processed my documents within seconds. However, as of this evening, I am experiencing an abnormal delay in processing times.

To illustrate the issue, a 25-page document that previously took only seconds to process now takes 37 minutes. The document in question is a simple text file with no unusual formatting or complex elements. It uses a standard Arial font.

This performance degradation is significantly impacting my workflow, as I am currently in the testing phase of a project and rely heavily on LlamaParse for efficient document processing.

I have attached the Job ID for your reference: fc9f3106-91cc-45bf-9062-46d0e256ab5d and 2f54470c-f240-4afd-a2cb-ca9bcf14d4bf

I would appreciate it if you could investigate this issue and provide a solution as soon as possible. Please let me know if you require any further information from my end.

**Comment by BharathxD** [comment]
The same is happening with our workflows. They have been slow for the last 2 weeks, and the performance has been degraded. Somehow, the files are now taking more than 3-4 minutes, whereas they usually took 30-40 seconds.

**Comment by BinaryBrain** [comment]
Hi @BharathxD 
Do you have a jobID for a job that took 3-4 minutes?

**Comment by Liboul** [comment]
> Hi [@BharathxD](https://github.com/BharathxD) Do you have a jobID for a job that took 3-4 minutes?

Same issue, here's an example, this is a one-page simple PDF with text only: 02c05083-fbb1-4fcf-b7b9-973d3f6ba2c1
It used to take a couple of seconds, now it's around 100x that 😅

**Comment by auktgs** [comment]
Same issue here

**Comment by goharShoukat** [comment]
I have a one page pdf with pure text. It's taking ages just to get the job started, let alone finishing it.

**Comment by GoffAC** [comment]
Seriously considering moving away from llama parse because of this. Most recently I have had a 17kb .docx that has taken 2.5 minutes to parse to markdown. What has happened? 

Anyone moved already or has collected options and wants to share?

**Comment by BinaryBrain** [comment]
Hey @GoffAC,
We've had a few issues when some specific conditions where met.
We released a patch yesterday that should fix this issue.
When did your issue occurred?

**Comment by GoffAC** [comment]
> Hey @GoffAC,
> We've had a few issues when some specific conditions where met.
> We released a patch yesterday that should fix this issue.
> When did your issue occurred?

Thanks for reaching out. 30 minutes ago. I can share details if needed?

**Comment by mehwishh247** [comment]
The issue is still there. The performance is quite slow even for a 1mb file. Along with this, there is an issue with reading guidelines as well. I have shared it in #620

**Comment by justme409** [comment]
yeah extremely slow for me too. unusable.

**Comment by r3rer3** [comment]
yea same here. it is a bit random. for the same file, it sometimes takes a long time, and sometimes not.

**Comment by DillonOLeary** [comment]
Also having the same problem. It's becoming a big deal when using LlamaCloud tools. I just uploaded like 4 small markdown files to index dcb7882c-ce47-42d1-84a7-8bfabc59abf3 and now I'm on the second hour of waiting for them to process
